# See example script at https://github.com/JuliaLang/Example.jl
language: julia

os:
  - linux
#  - osx

julia:
  - 1.2

branches:
  only:
    - master

matrix:
  - PYTHON=Conda-python

matrix:
  allow_failures:
    - julia: 1.2

notifications:
  email: false

git:
  depth: 99999999

script:
  travis_wait 30 julia --project --color=yes --check-bounds=yes -e 'using Pkg; Pkg.instantiate(); Pkg.build(); Pkg.test()';

jobs:
  include:
    - stage: "Documentation"
      julia: 1.2
      os: linux
#      before_script:
#        - julia --project -e 'using Pkg; '
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.add("PyCall"); Pkg.build("PyCall"); Pkg.add("PyPlot"); Pkg.build("PyPlot");  Pkg.add("Conda"); using Conda; Conda.add("matplotlib"); Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd())); Pkg.build("OITOOLS");
                    Pkg.instantiate();
                    Pkg.develop(PackageSpec(path=pwd()));
                    Pkg.build("OITOOLS");
                    Pkg.test()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
