# See example script at https://github.com/JuliaLang/Example.jl
language: julia

os:
  - linux
#  - osx

julia:
  - 1.2

branches:
  only:
    - master

matrix:
  allow_failures:
    - julia: 1.2

notifications:
  email: false

git:
  depth: 99999999

jobs:
  include:
    - stage: "Documentation"
      julia: 1.2
      os: linux
      script:
  #      - julia -e 'ENV["PYTHON"]=""; using Pkg; Pkg.add("PyCall"); Pkg.build("PyCall"); Pkg.add("PyPlot"); Pkg.add("Conda"); using Conda; Conda.add("matplotlib");'
        - julia --project=docs/ -e 'using Pkg; using Conda; Conda.add("matplotlib");
                                    Pkg.build("OITOOLS");
                                    Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
