[[AbstractFFTs]]
deps = ["LinearAlgebra"]
git-tree-sha1 = "380e36c66edfa099cd90116b24c1ce8cafccac40"
uuid = "621f4979-c628-5d54-868e-fcf4e3e8185c"
version = "0.4.1"

[[Compat]]
deps = ["Base64", "Dates", "DelimitedFiles", "Distributed", "InteractiveUtils", "LibGit2", "Libdl", "LinearAlgebra", "Markdown", "Mmap", "Pkg", "Printf", "REPL", "Random", "Serialization", "SharedArrays", "Sockets", "SparseArrays", "Statistics", "Test", "UUIDs", "Unicode"]
git-tree-sha1 = "ed2c4abadf84c53d9e58510b5fc48912c2336fbb"
uuid = "34da2185-b29b-5c13-b0c7-acf172513d20"
version = "2.2.0"

[[ArrayTools]]
git-tree-sha1 = "0be2baaba0c4ad44702551c8b9a97d86dd34d4bc"
repo-rev = "master"
repo-url = "https://github.com/emmt/ArrayTools.jl.git"
uuid = "1dc0ca97-c5ce-4e77-ac6d-c576ac9d7f27"
version = "0.1.0"

[[FITSIO]]
deps = ["BinaryProvider", "Libdl", "Printf"]
git-tree-sha1 = "6624bd0cdd03aa82df34d3eac56ab77ff696472e"
uuid = "525bcba6-941b-5504-bd06-fd0dc1a4d2eb"
version = "0.14.0"

[[LazyAlgebra]]
deps = ["AbstractFFTs", "ArrayTools", "Compat", "FFTW", "LinearAlgebra"]
git-tree-sha1 = "5c40ecd7cb5aade59d48212e09580066b04b03c6"
repo-rev = "master"
repo-url = "https://github.com/emmt/LazyAlgebra.jl.git"
uuid = "aeaa251e-9d76-11e9-311b-83636bf44738"
version = "0.1.0"

[[OIFITS]]
deps = ["Compat", "FITSIO"]
git-tree-sha1 = "19e5baa49adf9a60594b98795d8bbb5b74d8408f"
repo-rev = "t4"
repo-url = "https://github.com/fabienbaron/OIFITS.jl"
uuid = "53eb397e-dec1-5dcf-8dc9-2db916067267"
version = "0.4.0+"

[[OptimPackNextGen]]
deps = ["BinDeps", "Compat", "LazyAlgebra", "Libdl", "Test"]
git-tree-sha1 = "5363d2bfc88449b47b5783c6e3e9428d134a3280"
repo-rev = "master"
repo-url = "https://github.com/emmt/OptimPackNextGen.jl.git"
uuid = "b132a0d0-84c6-50b3-baad-5f8b1904065a"
version = "0.0.0"
